services:
  - type: web
    name: minecraft-bedrock-bot
    env: docker
    plan: free
    docker:
      dockerfilePath: ./Dockerfile
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
